language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.5.11
  - 5.6

matrix:
  allow_failures:
    - php: 5.6

script:
  - phpunit --configuration tests/phpunit.xml
  - php bin/vobject -h

before_script: composer install
